project_name: default
description: ''
fps: 30
mode: teleop
plotjuggler_enabled: true
cameras:
- name: cam_0
  type: v4l2
  device: 0
  width: 640
  height: 480
  fps: 30
  pixel_format: MJPG
  id_path: pci-0000:f1:00.4-usb-0:2:1.0
  channel: color
  options: {}
  channels: []
robots:
- name: arm_0
  type: airbot_play
  role: follower
  num_joints: 6
  device: can0
  direct_map_allowlist:
  - airbot_play
  options:
    target_tracking_mode: mit
- name: eef_g2_1
  type: airbot_g2
  role: follower
  num_joints: 1
  device: can0
  direct_map_allowlist:
  - airbot_e2b
  options:
    target_tracking_mode: mit
- name: arm_2
  type: airbot_play
  role: leader
  num_joints: 6
  device: can1
  direct_map_allowlist:
  - airbot_play
  options:
    target_tracking_mode: mit
- name: eef_e2b_3
  type: airbot_e2b
  role: leader
  num_joints: 1
  device: can1
  direct_map_allowlist:
  - airbot_g2
  options: {}
teleop_pairs:
- name: pair_0
  leader: arm_2
  follower: arm_0
  mapper: joint_direct
- name: pair_1
  leader: eef_e2b_3
  follower: eef_g2_1
  mapper: joint_direct
storage:
  root: ~/rollio_data
  lerobot_version: v2.1
encoder:
  video_codec: h264_nvenc
  depth_codec: ffv1
  background_workers: 1
upload:
  enabled: false
  endpoint: ''
  api_key_env: ''
async_pipeline:
  export_queue_size: 4
  telemetry_hz: 500
  control_hz: 500
  max_pending_episodes: 8
  allow_drop_preview_frames: true
controls:
  start_stop: ' '
  keep: k
  discard: d
